eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: authentication
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1/auth/** 

      - id: product
        uri: http://localhost:8082
        predicates:
        - Path=/api/v1/operation/**

      - id: batch
        uri: http://localhost:8083
        predicates:
        - Path=/api/v1/batch/**

      - id: batch
        uri: http://localhost:8084
        predicates:
        - Path=/api/v1/order/**
          